model:
  name: ASGGTM
  hparams:
    hidden_size: 128
    num_layers: 1
    dropout: 0
    bidirectional: True
    callbacks: EarlyStopping
    lr: 0.0001
    weight_decay: 0.001
  graph: False
  embedding: True  

  training:
    epochs: 500
    patience: 3
  device: cuda