model:
  name: GTM
  hparams:
    hidden_size: 64
    num_layers: 1
    dropout: 0
    bidirectional: True
    callbacks: EarlyStopping
    lr: 0.0001
    weight_decay: 0.001
  graph: False
  embedding: False
  training:
    epochs: 300
    patience: 50
    batch_size: 1