model:
  name: GTR
  hparams:
    hidden_size: 64
    num_layers: 1
    dropout: 0
    bidirectional: True
    callbacks: EarlyStopping
    lr: 0.0001
    weight_decay: 0.001
    loss: mse
  graph: False
  embedding: False
  training:
    epochs: 300
    patience: 3
  device: cuda
