model:
  name: SGGTM
  hparams:
    hidden_size: 64
    num_layers: 1
    dropout: 0
    bidirectional: True
    callbacks: EarlyStopping
    lr: 0.0001
    weight_decay: 0.001
  graph: True
  embedding: False
    
  training:
    epochs: 100
    patience: 50
    batch_size: 1
  device: cuda